site_name: agentic-ml
site_description: An agentic framework that tackles a data scientist's machine learning problems with LLM agents.
site_author: agentic-ml contributors
site_url: https://jcaste05.github.io/docs/agentic-ml/
repo_url: https://github.com/jcaste05/agentic-ml
repo_name: jcaste05/agentic-ml

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight

exclude_docs: |
  gen_ref_pages.py

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            members_order: source
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_section_style: table
